on: 
  repository_dispatch:
    types:
      - resource-published
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Status: ${{ github.event.client_payload.status }}"
        echo "Path: ${{ github.event.client_payload.path }}"
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Format path
        id: format
        uses: frabert/replace-string-action@v2
        with:
          pattern: '\.md'
          string: ${{ github.event.client_payload.path }}
          replace-with: ''
      - name: Notify Pipedream (JSON)
        if: ${{ endsWith(github.event.client_payload.path, '.json') }}
        run: |
          curl -d '{"text": "Just published: `${{ github.event.client_payload.path }}`"}' \
             -H "Content-Type: application/json"  \
             ${{ secrets.PIPEDREAM_ENPOINT }}
      - name: Notify Pipedream (Markdown)
        if: ${{ endsWith(github.event.client_payload.path, '.md') }}
        run: |
          curl -d '{"text": "Just published: https://www.hlx.live${{ steps.format.outputs.replaced }}"' \
             -H "Content-Type: application/json"  \
             ${{ secrets.PIPEDREAM_ENPOINT }}
